services:
  bambictf:
    image: ghcr.io/enowars/bambictf:latest
    environment:
    - HCLOUD_TOKEN=${HCLOUD_TOKEN}                # for packer
    - TF_VAR_HCLOUD_TOKEN=${HCLOUD_TOKEN}         # for terraform
    - TF_VAR_HETZNERDNS_TOKEN=${HETZNERDNS_TOKEN} # for terraform
    volumes:
    - ".:/bambictf"
