---
  - name: Install all the needed programs and do an update
    apt:
      name: "{{ program_list }}"
      force_apt_get: yes
      autoremove: yes
      cache_valid_time: 3000
      state: present
