---
- name: Increase max_map_count
  sysctl:
    name: vm.max_map_count
    value: "262144"
    sysctl_set: true

- name: Install tcpdump
  apt:
    name: tcpdump
    state: present
    update_cache: true

- name: Copy over the enodump unit
  copy:
    src: enodump.service
    dest: /etc/systemd/system/enodump.service
    mode: "0644"
  changed_when: false

- name: Ensure /etc/apparmor.d/disable exists
  file:
    path: /etc/apparmor.d/disable
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Disable tcpdump apparmor profile
  file:
    path: /etc/apparmor.d/disable/usr.bin.tcpdump
    src: /etc/apparmor.d/usr.bin.tcpdump
    state: link
    force: true
    follow: false

- name: Ensure /services/EnoMoloch exists
  file:
    path: /services/EnoMoloch
    state: directory
    mode: "0755"

- name: Copy over the EnoMoloch docker-compose file
  copy:
    src: docker-compose.yml
    dest: /services/EnoMoloch/docker-compose.yml
    mode: "0644"
  changed_when: false

- name: Pull EnoMoloch images
  shell: docker compose pull # noqa: command-instead-of-shell
  args:
    chdir: /services/EnoMoloch

- name: Reload system daemon
  systemd:
    name: "enodump" # ansible <2.4 always requires 'name'
    daemon_reload: true

- name: Ensure /pcaps exists
  file:
    path: /pcaps
    state: directory
    owner: tcpdump
    group: tcpdump
    mode: "0755" # 0644 is not enough

- name: Enable and start enodump
  service:
    name: enodump
    enabled: true

- name: "Block access to moloch from game interface"
  iptables:
    chain: DOCKER-USER
    in_interface: game
    protocol: tcp
    source: "10.13.0.0/24"
    destination_port: "8005"
    jump: DROP

- name: Persist iptables config
  include_role:
    name: "iptables_persistent"
