version: '3'
services:
  moloch:
    image: ghcr.io/enoflag/enomoloch:latest
    ports:
      - 8005:8005
    volumes:
      - "/pcaps:/data/moloch/raw"
    environment:
      - "MOLOCH_PASSWORD=moloch"
  elasticsearchmoloch:
    image: elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
