version: '3'
services:
  moloch:
    image: ghcr.io/enoflag/enoarkime:5.3.0
    ports:
      - 8005:8005
    volumes:
      - "/pcaps:/opt/arkime/raw"
  elasticsearch:
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
