version: '3'
services:
  moloch:
    image: ghcr.io/enoflag/enoarkime:latest
    ports:
      - 8005:8005
    volumes:
      - "/pcaps:/data/moloch/raw"
  elasticsearchmoloch:
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
