---
- name: "Install openvpn"
  apt:
    package:
      - openvpn
      - unzip

- name: copy zipped team VPN configs
  copy:
    src: "{{ zip_directory }}"
    dest: /root

- name: allow openvpn input traffic
  iptables:
    chain: INPUT
    in_interface: eth0
    destination_port: "30001:32000"
    protocol: udp
    jump: ACCEPT

- name: persist iptables config
  shell: "iptables-save > /etc/iptables/rules.v4"
