---
- name: allow openvpn input traffic
  iptables:
    chain: INPUT
    in_interface: eth0
    destination_port: "30001"
    protocol: udp
    jump: ACCEPT

- name: persist iptables config
  include_role:
    name: "iptables-persistent"
