---
- name: Increase max_map_count
  sysctl:
    name: vm.max_map_count
    value: "262144"
    sysctl_set: true

- name: Install git dependency
  apt:
    name: ["git"]
    state: present

- name: Clone EnoELK
  git:
    repo: "https://github.com/enowars/EnoELK.git"
    dest: /services/EnoELK

- name: Pull ELK images
  docker_compose:
    pull: true
    project_src: /services/EnoELK

- name: Allow wireguard input traffic (internal)
  iptables:
    chain: INPUT
    in_interface: eth0
    destination_port: "51821"
    protocol: udp
    jump: ACCEPT

- name: Persist iptables config
  include_role:
    name: "iptables_persistent"
