---
- name: Increase max_map_count
  sysctl:
    name: vm.max_map_count
    value: "262144"
    sysctl_set: true

- name: Copy EnoELK
  copy:
    src: EnoELK/
    dest: /services/EnoELK/
    mode: preserve

- name: Pull ELK images
  shell: docker compose pull # noqa: command-instead-of-shell
  args:
    chdir: /services/EnoELK

- name: Allow wireguard input traffic (internal)
  iptables:
    chain: INPUT
    in_interface: eth0
    destination_port: "51821"
    protocol: udp
    jump: ACCEPT

- name: Persist iptables config
  include_role:
    name: "iptables_persistent"
