---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml

    roles:
      - docker
      - vuln_services
      - bambi-ssh-keys
      - firewall
      - docker-block-external
      - wireguard
      - enomoloch
      - bambixploit
      - role: programs
        vars:
          program_list:
            - tmux
            - unzip
            - git
            - python3-pip
      - role: pip-packages
        vars:
          pip_list:
            - pwntools
