---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml
      - static.yml

    roles:
      - base
      - docker
      - vuln_services
      - docker-block-external
      - enomoloch
      - bambixploit
      - root-password-login
      - role: programs
        vars:
          program_list:
            - unzip
      - role: pip-packages
        vars:
          pip_list:
            - pwntools
