---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml
      - static.yml

    roles:
      - bambi-ssh-keys
      - firewall
      - wireguard
      - enoengine
      - wireguard_engine
      - filebeat
      - journalbeat
      - metricbeat
      - docker-block-external
      - tmux
