---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml
      - static.yml

    roles:
      - bambi-ssh-keys
      - firewall
      - wireguard
      - enoelk
      - docker-block-external
      - wireguard_elk
      - filebeat
      - journalbeat
      - metricbeat
      - role: programs
        vars:
          program_list:
            - "tmux"
            - "git"
