---
- name: Bambi ELK
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - config_bambi.yml
    - static.yml

  roles:
    - base
    - enoelk
    - docker_block_external
    - role: wireguard_configs
      vars:
        wireguard_configs_dir: elk
    - filebeat
    - journalbeat
    - metricbeat
