---
- name: Bambi Vulnbox
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - config_bambi.yml
    - static.yml

  roles:
    - base
    - docker
    - vuln_services
    - docker_block_external
    - vulnbox_enomoloch
    - bambixploit
    - root_password_login
    - role: programs
      vars:
        programs_list:
          - unzip
    - role: pip_packages
      vars:
        pip_packages_list:
          - pwntools
