---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml

    roles:
      - hetzner-base
      - bambi-ssh-keys
      - firewall
      - role: internal-routes
        vars:
          gateway: 192.168.0.1
      - enoengine
      - enoelk
      - enoscoreboard
      - role: filebeat
        vars:
          elk: 192.168.1.0
      - role: journalbeat
        vars:
          elk: 192.168.1.0
      - role: metricbeat
        vars:
          elk: 192.168.1.0
      - docker-block-external
      - role: programs
        vars:
          program_list: "tmux"
