---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml
      - static.yml

    roles:
      - base
      - enoengine
      - role: wireguard_configs
        vars:
          config_dir: engine
      - filebeat
      - journalbeat
      - metricbeat
      - docker-block-external
