---
- name: Bambi Engine
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - config_bambi.yml
    - static.yml

  roles:
    - base
    - enoengine
    - role: wireguard_configs
      vars:
        wireguard_configs_dir: engine
    - filebeat
    - journalbeat
    - metricbeat
    - docker_block_external
    - role: programs
      vars:
        programs_list:
          - tcpdump
          - ncdu
          - iftop
          - tmux
