---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml
      - static.yml

    roles:
      - docker
      - vuln_services
      - bambi-ssh-keys
      - firewall
      - docker-block-external
      - wireguard
      - enomoloch
      - bambixploit
      - tmux
      - role: programs
        vars:
          program_list:
            - unzip
      - role: pip-packages
        vars:
          pip_list:
            - pwntools
