---
- name: Create /services
  file:
    path: /services
    state: directory
    mode: "0755"

- name: Configure docker http proxy
  shell: |
    echo '{
      "proxies": {
        "http-proxy": "http://proxy.prod.bambi.ovh:3128",
        "https-proxy": "http://proxy.prod.bambi.ovh:3128"
      },
      "log-driver": "json-file",
        "log-opts": {
          "max-size": "300m",
          "max-file": "3"
        },
        "default-address-pools": [{
          "base": "172.17.0.0/16",
          "size": 24
        }]
    }' > /etc/docker/daemon.json
    systemctl restart docker

- name: Clean local services cache
  become: false
  file:
    path: ./services/{{ inventory_hostname }}/dockered_vulnerable_services
    state: absent
  delegate_to: localhost

- name: Clone services locally
  become: false
  git: # noqa: latest
    repo: "{{ item.value }}"
    dest: ./services/{{ inventory_hostname }}/dockered_vulnerable_services/{{ item.key }}
    key_file: "{{ playbook_dir }}/../id_ed25519"
    accept_hostkey: true
  with_dict: "{{ vulnerable_services }}"
  delegate_to: localhost

- name: Copy services to vulnbox
  synchronize:
    src: ./services/{{ inventory_hostname }}/dockered_vulnerable_services/{{ item.key }}/service/
    dest: /services/{{ item.key }}
  with_dict: "{{ vulnerable_services }}"

- name: Pull/build service
  shell: docker compose pull && docker compose build
  args:
    chdir: /services/{{ item.key }}
  with_dict: "{{ vulnerable_services }}"
