---
- name: Create /services
  file:
    path: /services
    state: directory
    mode: "0755"

- name: Clean local services cache
  become: false
  file:
    delegate_to: localhost
    path: ./services/{{ inventory_hostname }}/dockered_vulnerable_services
    state: absent

- name: Clone services locally
  become: false
  git: # noqa: latest
    delegate_to: localhost
    repo: "{{ item.value }}"
    dest: ./services/{{ inventory_hostname }}/dockered_vulnerable_services/{{ item.key }}
    key_file: "{{ playbook_dir }}/../id_ed25519"
    accept_hostkey: true
  with_dict: "{{ vulnerable_services }}"

- name: Copy services to vulnbox
  synchronize:
    src: ./services/{{ inventory_hostname }}/dockered_vulnerable_services/{{ item.key }}/service/
    dest: /services/{{ item.key }}
  with_dict: "{{ vulnerable_services }}"

- name: Pull/build service
  shell: docker compose pull && docker compose build
  args:
    chdir: /services/{{ item.key }}
  with_dict: "{{ vulnerable_services }}"
