---
- name: Allow wireguard input traffic (internal)
  iptables:
    chain: INPUT
    in_interface: eth0
    destination_port: "51821"
    protocol: udp
    jump: ACCEPT

# TODO fixme @ldruschk
- shell: iptables -A INPUT -i br-+ -p tcp -m tcp --dport 9200 -j ACCEPT # noqa: command-instead-of-shell
- shell: iptables -A INPUT -i internal -p tcp -m tcp --dport 9300 -j ACCEPT # noqa: command-instead-of-shell
- shell: iptables -A INPUT -i internal -p tcp -m tcp --dport 8005 -j ACCEPT # noqa: command-instead-of-shell

- name: Persist iptables config
  include_role:
    name: "iptables_persistent"

- name: Increase max_map_count
  sysctl:
    name: vm.max_map_count
    value: "262144"
    sysctl_set: true

- name: Copy BambiArkimeElasticsearch
  copy:
    src: BambiArkimeElasticsearch/
    dest: /services/BambiArkimeElasticsearch/
    mode: preserve

- name: Pull BambiArkimeElasticsearch
  shell: docker compose pull # noqa: command-instead-of-shell
  args:
    chdir: /services/BambiArkimeElasticsearch

- name: Copy BambiArkime
  copy:
    src: BambiArkime/
    dest: /services/BambiArkime/
    mode: preserve

- name: Pull BambiArkime
  shell: docker compose pull # noqa: command-instead-of-shell
  args:
    chdir: /services/BambiArkime
