FROM ghcr.io/enoflag/enoarkime:5.1.0

COPY arkime-viewer.sh arkime-viewer.sh
COPY arkime-capture.sh arkime-capture.sh
COPY docker-entrypoint.sh docker-entrypoint.sh
COPY config.ini /opt/arkime/etc/config.ini
