name: Packer build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/enowars/bambictf:latest
          outputs: type=docker,dest=/tmp/bambictf.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bambictf
          path: /tmp/bambictf.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: bambictf
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/bambictf.tar
          docker image ls -a